
CREATE TABLE diagnose
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_diagnose PRIMARY KEY (id)
);

CREATE TABLE session
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    diagnose_id BIGINT,
    user_id     BIGINT,
    status      VARCHAR(255),
    CONSTRAINT pk_session PRIMARY KEY (id)
);

CREATE TABLE symptom
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    session_id BIGINT,
    symptom_id BIGINT,
    grade      VARCHAR(255),
    CONSTRAINT pk_symptom PRIMARY KEY (id)
);

CREATE TABLE symptom_1
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_symptom_1 PRIMARY KEY (id)
);

CREATE TABLE "user"
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(30),
    last_name  VARCHAR(30),
    username   VARCHAR(30),
    password   VARCHAR(255),
    bio        VARCHAR(1000),
    role       VARCHAR(255),
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE session
    ADD CONSTRAINT FK_SESSION_ON_DIAGNOSE FOREIGN KEY (diagnose_id) REFERENCES diagnose (id);

ALTER TABLE session
    ADD CONSTRAINT FK_SESSION_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

ALTER TABLE symptom
    ADD CONSTRAINT FK_SYMPTOM_ON_SESSION FOREIGN KEY (session_id) REFERENCES session (id);

ALTER TABLE symptom
    ADD CONSTRAINT FK_SYMPTOM_ON_SYMPTOM FOREIGN KEY (symptom_id) REFERENCES symptom_1 (id);